### ISSUE TITLE
Cannot start the server with a tc-config file on Windows

### ISSUE THREAD

**Issue by aurbroszniowski** [Terracotta-OSS/terracotta-core#251] opened 2016-06-30 20:27 UTC
When starting the server from the 3.1.0 kit, and specifying a tc-config xml, the server doesn't recognise it and doesn't start (-f or --config doesn't work)
See attached screenshot (with verification that the file does exist)

![custom-tc-config](https://cloud.githubusercontent.com/assets/1264251/16503096/af4d870c-3f11-11e6-9dd8-1e6320d1551d.png)

**Comment by jd0-sag** [comment] 2016-06-30 20:52
Does it work if you specify a relative path or a fully path, starting with the drive letter?

The reason why I ask is that it looks like the path you are giving is being interpreted as a relative path and just appended to the current directory.

**Comment by esebasti** [comment] 2016-06-30 21:04
I don't see this problem on my windows machine when I specify full path for config.

**Comment by jd0-sag** [comment] 2016-06-30 21:11
I am going to close this since it seems to be working as designed.  A Windows path with "\" prefix will still be considered relative.

Source in the Javadoc:  http://docs.oracle.com/javase/7/docs/api/java/io/File.html#isAbsolute()

`On Microsoft Windows systems, a pathname is absolute if its prefix is a drive specifier followed by "\\", or if its prefix is "\\\\".`

**Closed by jd0-sag** 2016-06-30 21:11 UTC
