### ISSUE TITLE
No parallelism on sync

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#354] opened 2016-11-02 14:23 UTC
Sync operations are distributed across threads(4 on my machine) based on concurrency key but they get executed serially. It is observed during ehcache sync test.

**Comment by jd0-sag** [comment] 2016-11-02 14:35
The current design is that we only synchronize one key at a time, in the order they are provided.  This is deliberate since it allows the entity to do things like send critical meta-data in the first key, for example.

That said, if you are running messages _during_ the sync, messages to keys not currently mid-sync should still be allowed to run.  Additionally, they will only run on the active if the key hasn't yet been synced but will run on any passives which have synced the key (even though another key might still be mid-sync).

**Comment by jd0-sag** [comment] 2016-11-02 15:31
Can you verify that the invokes still run concurrently with the sync?  If that works, we will close this as working as designed.

**Comment by esebasti** [comment] 2016-11-03 21:07
Closing it now as the original one reported here is by design. I will run some tests with client sending messages when sync occurs and open new issue if anything doesn't work there as expected.

**Closed** 2016-11-03 21:07 UTC
